### ISSUE TITLE
[EPIC] Version 4 release

### ISSUE THREAD

**Issue by balcsida** [webextension-toolbox/webextension-toolbox#145]
After getting feedback from the community I believe adding react presets to core was not a good idea.

Therefore this PR introduces some breaking changes, that opens the this toolbox for frameworks like vue, svelte, angular and typescript.

## What changes?

From now on webextension-toolbox only includes relevant presets needed to create a browser extension. Actually the only preset that is included is preset-env. This is preconfigured by the [binary](https://github.com/webextension-toolbox/webextension-toolbox/blob/master/bin/webextension-toolbox). 

It configures the right `vendor` and the `vendorVersion`.

* `vendor`:  `chrome`, `firefox`, `edge`, etc.
* `vendorVersion`: if not provided webextension-toolbox uses the last 3 Versions of the current vendor.

## How do I use react?

1. `npm install @babel/preset-react --save-dev`
2. Create a `.babelrc` file next to your `package.json` file and insert the following contents:

```js
{
  "presets": [
    "@babel/preset-react"
  ]
}
```

## Todo

- [ ] Update docs
- [ ] Write migration guide
- [ ] Implement react promt in [generator-web-extension](https://github.com/webextension-toolbox/generator-web-extension)
- [ ] Release as major version
- [ ] Evaluate if we still need the other presets
- [ ] Create a legacy preset
